server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: books-service
              uri: lb://books-service
              predicates:
                - Path=/books/**,/authors/**
              filters:
                - StripPrefix=0

            - id: users-service
              uri: lb://users-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=0

            - id: borrowing-service
              uri: lb://borrowing-service
              predicates:
                - Path=/borrowings/**
              filters:
                - StripPrefix=0

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
