server:
  port: 8080

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: books-service
          uri: http://localhost:8081
          predicates:
            - Path=/books/**,/authors/**
          filters:
            - StripPrefix=0

        - id: users-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0

        - id: borrowing-service
          uri: http://localhost:8082
          predicates:
            - Path=/borrowings/**
          filters:
            - StripPrefix=0

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
