server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
